files/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('youtube.urls'))
]

youtube/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.conf.urls.static import static



app_name = 'youtube'

urlpatterns = [
    path('',views.index,name='index'),
    path('upload/',views.uploads,name='upload'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

youtube/models.py
from django.db import models

# Create your models here.

youtube/views.py
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
# Create your views here.
def index(request):
    return render(request,'youtube/index.html')

def uploads(request):
    if request.method == 'POST':
        uploadedFiles = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploadedFiles.name,uploadedFiles)
        url = fs.url(name)
    context = {'url':url}
    return render(request,'youtube/upload.html',context)

youtube/templates/youtube/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark  ">
    <a class="navbar-brand" href="#"> Youtue</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'youtube:index' %}">Home <span class="sr-only">(current)</span> </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'youtube:upload' %}">Upload <span class="sr-only">(current)</span> </a>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block main_work %}

    {% endblock main_work %}
</div>
</body>
</html>

youtube/templates/youtube/index.html
{% extends "youtube/base.html" %}
{% load static %}

{% block main_work %}

  <h2>THis is the index page </h2>
{% endblock main_work %}

youtube/templates/youtube/upload.html
{% extends "youtube/base.html" %}
{% load static %}

{% block main_work %}
<div class="row">url
    <div class="col-md-2"></div>

    <div class="col-md-8 bg-light" style="padding: 15px;">
        <h4>This is where you upload from </h4>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" class="input" name="document" id="">
            <button type="submit" class="btn btn-outline-success">upload</button>
        </form>
        {% if url  %}
        <p>File path you uploaded : <a href="{{ url }}">{{url}}</a></p>
        {% endif %}
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock main_work %}